package com.capstone.pedotan.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class History(
    val id: Int,
    val fieldId: Int,
    val timestamp: String,
    val nitrogen: String,
    val phosphorous: String,
    val potassium: String,
    val curahhujan: String,
    val ph: String,
    val kelembaban: String,
    val suhu: String,
    val penyakit: String,
) : Parcelable

object HistoryData {
    val histories = listOf(
        History(
            1,
            1,
            "2021-08-01 08:32:23",
            "Cukup",
            "Cukup",
            "Cukup",
            "202",
            "6",
            "82",
            "20",
            "Sehat",
        ),
        History(
            2,
            1,
            "2021-08-02 09:42:22",
            "Cukup",
            "Kurang",
            "Cukup",
            "182",
            "6",
            "82",
            "19",
            "black_rot",
        ),
        History(
            3,
            1,
            "2021-08-03 07:50:32",
            "Cukup",
            "Cukup",
            "Kurang",
            "202",
            "6",
            "82",
            "22",
            "leaf_blast",
        ),
        History(
            4,
            1,
            "2021-08-04 09:10:32",
            "Cukup",
            "Cukup",
            "Cukup",
            "198",
            "5",
            "82",
            "20",
            "Sehat",
        ),
        History(
            5,
            1,
            "2021-08-05 09:12:34",
            "Cukup",
            "Cukup",
            "Cukup",
            "212",
            "6",
            "77",
            "20",
            "Sehat",
        ),
        History(
            6,
            1,
            "2021-08-06 10:31:51",
            "Kurang",
            "Cukup",
            "Cukup",
            "222",
            "7",
            "89",
            "18",
            "Sehat",
        ),
        History(
            7,
            2,
            "2021-08-07 10:23:53",
            "Cukup",
            "Cukup",
            "Cukup",
            "223",
            "6",
            "77",
            "20",
            "Sehat",
        ),
        History(
            8,
            2,
            "2021-08-08 08:30:40",
            "Cukup",
            "Cukup",
            "Cukup",
            "232",
            "6",
            "89",
            "18",
            "Sehat",
        ),
        History(
            9,
            2,
            "2021-08-09 08:18:24",
            "Cukup",
            "Cukup",
            "Cukup",
            "212",
            "6",
            "87",
            "20",
            "Sehat",
        ),
        History(
            10,
            2,
            "2021-08-10 09:20:33",
            "Cukup",
            "Kurang",
            "Cukup",
            "240",
            "6",
            "88",
            "22",
            "leaf_mold",
        ),
    )
}